### ISSUE TITLE
write_file in core.py

### ISSUE THREAD

**Issue by dethfeet** [jbeluch/python-brightcove#1]
Hi,

thanks for your api I am trying to use it for  a plugin and stumbled accross the following:

in core.py line 22 is:
write_file(url, conn.info(), resp)" 

This does not work on OSX: 
NameError: global name 'write_file' is not defined

It seems to be used for development and not needed for using the api.

Cheers

**Comment by dethfeet** [comment]
Sorry, just saw that this has already been fixed. But it is not in the official repo: 
http://xbmc.git.sourceforge.net/git/gitweb.cgi?p=xbmc/scripts;a=blob_plain;f=script.module.brightcove/lib/brightcove/core.py;hb=refs/heads/eden

Maybe you can send a new pull request...

**Comment by jbeluch** [comment]
You are correct. I'll send a new PR to the mailing list.

**Comment by jbeluch** [comment]
The newest version (1.1.1) has been pulled into the official Eden repository.
